default: &default
  adapter: postgresql
  pool: 5
  port: 5432
  username: <%= ENV['BOOKHUNTER_DATABASE_USERNAME'] %>
  password: <%= ENV['BOOKHUNTER_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: book-hunter

test:
  <<: *default
  database: book-hunter

production:
  <<: *default
  database: book-hunter
