Point.create(level: 1, parent: 0, name: 'astronomy', caption_ru: 'Астрономия')
Point.create(level: 1, parent: 0, name: 'business', caption_ru: 'Бизнес')
Point.create(level: 1, parent: 0, name: 'biography', caption_ru: 'Биографии')
Point.create(level: 1, parent: 0, name: 'web-development', caption_ru: 'Веб-разработка')
Point.create(level: 1, parent: 0, name: 'gis', caption_ru: 'ДЗЗ')
Point.create(level: 1, parent: 0, name: 'design', caption_ru: 'Дизайн')
Point.create(level: 1, parent: 0, name: 'languages', caption_ru: 'Иностранные языки')
Point.create(level: 1, parent: 0, name: 'ai', caption_ru: 'ИИ')
Point.create(level: 1, parent: 0, name: 'cooking', caption_ru: 'Кулинария')
Point.create(level: 1, parent: 0, name: 'programming', caption_ru: 'Программирование')
Point.create(level: 1, parent: 0, name: 'photo', caption_ru: 'Фотография')
Point.create(level: 1, parent: 0, name: 'literature', caption_ru: 'Худ. литература')
Point.create(level: 1, parent: 0, name: 'signals', caption_ru: 'ЦОС')
Point.create(level: 1, parent: 0, name: 'electronics', caption_ru: 'Электроника')
Point.create(level: 1, parent: 0, name: 'poisons', caption_ru: 'Яды')
Point.create(level: 2, parent: 4, name: 'common', caption_ru: 'Общие материалы')
Point.create(level: 2, parent: 4, name: 'html', caption_ru: 'HTML')
Point.create(level: 2, parent: 4, name: 'css', caption_ru: 'CSS')
Point.create(level: 2, parent: 4, name: 'js', caption_ru: 'JavaScript')
Point.create(level: 2, parent: 4, name: 'php', caption_ru: 'PHP')
Point.create(level: 2, parent: 4, name: 'frameworks', caption_ru: 'Frameworks')
Point.create(level: 3, parent: 19, name: 'script', caption_ru: 'JavaScript')
Point.create(level: 3, parent: 19, name: 'jquery', caption_ru: 'JQuery')
Point.create(level: 3, parent: 19, name: 'coffee', caption_ru: 'CoffeeScript')
Point.create(level: 3, parent: 21, name: 'django', caption_ru: 'Django')
Point.create(level: 3, parent: 21, name: 'rails', caption_ru: 'Ruby on Rails')
Point.create(level: 3, parent: 21, name: 'angular', caption_ru: 'AngularJS')
Point.create(level: 4, parent: 25, name: 'python', caption_ru: 'Python')
Point.create(level: 4, parent: 26, name: 'ruby', caption_ru: 'Ruby')
Point.create(level: 4, parent: 25, name: 'dj', caption_ru: 'Django')
Point.create(level: 4, parent: 26, name: 'Rails', caption_ru: 'Rails')